### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by pnatarajan9** [nf-core/tfactivity#15]
### Description of the bug

TF activity- https://github.com/nf-core/tfactivity
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━  90% • 18/20 completed
biocontainers/stare… FATAL:   While making image from oci registry: error fetc… 
CRITICAL The container "biocontainers/stare-abc:1.0.4--haf6292c_1" is           
         unavailable.                                                           
         WARNING: Couldn't use cached digest for registry: HEAD                 
         https://index.docker.io/v2/biocontainers/stare-abc/manifests/1.0.4--haf
         6292c_1: unexpected status code 401 Unauthorized (HEAD responses have  
         no body, use GET for details)                                          
         WARNING: Falling back to direct digest.                                
         FATAL:   While making image from oci registry: error fetching image to 
         cache: failed to get checksum for                                      
         docker://biocontainers/stare-abc:1.0.4--haf6292c_1: GET                
         https://index.docker.io/v2/biocontainers/stare-abc/manifests/1.0.4--haf
         6292c_1: UNAUTHORIZED: authentication required; [map[Action:pull Class:
         Name:biocontainers/stare-abc Type:repository]]      

### System information

Nextflow version - 23.04.1
nf-core version: 2.7.2
Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-28-generic x86_64)
nf-core tfactivity - dev version

**Comment by nictru** [comment]
Hello @pnatarajan9
Good to see you here! You are one of the first external users of our pipeline - it is still under heavy development, so be aware that there might be more problems coming up. But we appreciate test feedback very much :)

I identified the reason for your problem and pushed a fix. Please make sure to pull the latest version of the pipeline (`nextflow pull nf-core/tfactivity`, should be commit `a05a270` then). If it solves your issue, feel free to close it.
