### ISSUE TITLE
Replace ROSE with bedtools

### ISSUE THREAD

**Issue by LeonHafner** [nf-core/tfactivity#9]
### Description of feature

As commented in #5, we should check if it is possible to remove the ROSE codebase of 620 lines and replace it by some bedtools processes.

              @LeonHafner we should investigate if we can replace this with a sequence of `bedtools` commands, which would reduce the amount of code drastically

_Originally posted by @nictru in https://github.com/nf-core/tfactivity/issues/5#issuecomment-2077152326_

**Comment by nictru** [comment]
I just went through the logic of ROSE again and as far as I can tell, it builds TSS loci based on the start of all transcripts in the `genepred` file, then removes all fully contained candidate regions and then merges all candidate regions within a certain range. Then it reverts the merging for all regions overlapping more than 2 unique TSSs. 


Based on this, I would suggest a workflow like this:
1. Keep the GTF to genepred conversion as it is, as it is helpful for transcript extraction (except step 2 is easily possible based on GTF)
2. Convert the genepred file to a bed file, which resembles the TSS windows (depending on strand, either `start+/-tss_window` or `end+/-tss_window`, can probably be done using `GAWK` or `BIOAWK` nf-core modules
3. `bedtools subtract -a candidates.bed -b tss.bed -f 1`
4. `bedtools merge -d 12500 -i subtracted.bed`
5. Don't have an idea yet about the reverting of the regions with more than 2 TSS overlaps (is it even necessary?)

I think it is good to mention that the removal of regions close to TSS is most likely done to exclude promoter regions. If we would also want to investigate candidate promoter regions, we would only have to invert this logic. For this we would have to replace `bedtools subtract` with `bedtools intersect` in step 4.
